language: cpp
os: linux
dist: focal
env:
    - CTEST_OUTPUT_ON_FAILURE=1
compiler: gcc
before_install:
    - ./scripts/dependencies.sh
    - sudo sed -i -e 's/\(host.*\)trust/\1md5/g' /etc/postgresql/*/main/pg_hba.conf
    - sudo service postgresql restart
    - sleep 1
git:
    submodules: true
